# Generated by Django 4.2.3 on 2023-08-01 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devices',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deviceusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceusers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='odooinstances',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 1, 7, 54, 41, 796241, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odooinstances',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odoo.devices'),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odoo.deviceusers'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='devices',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='port',
            field=models.IntegerField(default=4370),
        ),
        migrations.AlterField(
            model_name='devices',
            name='timeout',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='deviceusers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='odooinstances',
            name='batch_size',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='odooinstances',
            name='timeout',
            field=models.IntegerField(default=60),
        ),
    ]
